simons-public/protonfixes

protonfixes/util.py

- `log.info('Running protonfixes')` removed as duplicate
- New utils for Proton env vars (see user_settings.py)
* util.disable_dxvk()
* util.disable_esync()
* util.disable_d3d11()
* util.disable_d3d10()
- New utils for WINEDLLOVERRIDES
* util.winedll_override(dll, dtype)
where "dll" - DLL name (e.g. d3d11)
"dtype" = one of ['','b','n'] - equals to [disabled, builtin, native]
* util.disable_nvapi()
- New generic util
* util.get_game_install_path()

Extended utils

---

.pylintrc
.travis.yml
protonfixes/fix.py
protonfixes/gamefixes/2620.py
protonfixes/gamefixes/409720.py
protonfixes/splash.py
protonfixes/util.py
tests/test_utils.py

This PR introduces Travis file to trigger automatic linting on every push and blank default pylintrc file modified to suppress I1011/E1011/bad-option-value (depending on pylint version).
Thanks to pylint, in the process of making build green, I found a bug in Call of Duty gamefix.
@simons-public Can you enable Travis for this repo? This would trigger automatic linking on all future PRs :)

Run pylint using Travis

---

protonfixes/util.py

This will create and use temporary DXVK configuration file.
If dxvk.conf already exists in game directory and contains
changed options -- they will be appended to created file.
Example:
```python
from protonfixes import util
util.set_dxvk_option('d3d10.enable', 'False')
```
```sh
ProtonFixes[19253] INFO: Creating new DXVK config
ProtonFixes[19253] INFO: Adding env: DXVK_CONFIG_FILE=/tmp/protonfixes_dxvk.conf
ProtonFixes[19253] INFO: Addinging DXVK option: d3d10.enable = False
```
```
info:  DXVK: v0.90-8-g6558b27
info:  Found config file: /tmp/protonfixes_dxvk.conf
info:  Effective configuration:
info:    d3d10.enable = False
info:    session = 18033
info:    dxgi.maxFrameLatency = 1
```

Added a set_dxvk_option util

---

protonfixes/corefonts.py

Hardlinks are not allowed between partitions with a different inode number. This commit uses symlinks instead. See #30

Use symlinks instead of hardlinks to link corefonts

---

protonfixes/gamefixes/35450.py

Added audio fix (install xact from winetricks) for Rising Storm/Red Orchestra 2 Multiplayer (Unreal Engine 3 game) based on the Spacewar fix, probably can be applied to other UE3 games with similar problems.

Rising Storm/Red Orchestra 2 Multiplayer (35450)

---

protonfixes/gamefixes/verbs/force_gpu.verb
protonfixes/gamefixes/verbs/force_gpu=amd.verb
protonfixes/gamefixes/verbs/force_gpu=no.verb
protonfixes/gamefixes/verbs/force_gpu=nvidia.verb
protonfixes/util.py

* Custom winetricks verbs support
Partially resolves simons-public#41 
` util.protontricks('winetricks_verb')` will search for a `$winetricks_verb$.verb` file in
* localfixes/verbs/ - local custom verbs
* gamefixes/verbs/ - builtin custom verbs
* Custom winetricks verb example
This will force AMD or Nvidia GPU via registry
Example:
```
util.protontricks('force_gpu=nvidia')
```
Supported variants:
`force_gpu=amd`, `force_gpu=nvidia` and `force_gpu=no`

Added custom winetricks verbs support

---

protonfixes/gamefixes/17300.py

Implement fixes for known issues with Crysis, and enables DX10 support if Vulkan support is present.

Add fixes for Crysis

---

protonfixes/util.py

Sometimes `winetricks` performs a strange things, so
very likely it should wait for `wineserver` to quit.
Not sure, but it can also help #19, or otherwise there
should be one more check for a prefix existence.

Possible fix for a rare winetricks fail

---

protonfixes/util.py

* duplicate variables in section
```ini
var1=val1
var2=val2
var1=
```
* multiline values
```ini
var1=Hello,
World
var2=val2
```

Fixed non-strict INI files parsing

---

protonfixes/util.py

`util.protonversion()` currently returns the version name (e.g. `Proton 3.16`)
`util.protonversion(True)` will return the version timestamp (e.g. `1544476838`)
Resolves: #63

Return Proton version timestamp

---

protonfixes/util.py

The new proton version timestamp added in #65 is being returned as `str`. This should `int` instead.

Return Proton version timestamp as int not str

---

protonfixes/gamefixes/424840.py
protonfixes/gamefixes/493200.py

With FAudio the xact audio is not needed anymore for many games. This updates the fixes for Little Nightmares and RiME to only be applied if used Proton version is older than 3.16-5.

Only use xact fix if Proton version prior 3.16-5 (424840, 493200)

---

protonfixes/gamefixes/200260.py
protonfixes/gamefixes/211420.py
protonfixes/gamefixes/220440.py
protonfixes/gamefixes/268910.py
protonfixes/gamefixes/35140.py

Fixed:
Cuphead - data.unity3d missing errors on some configuration
Batman Arkham City - fully working in DX9, except finding correct locales.
Batman Arkham Asylum - working, but needs controller fix
DMC: Devil May Cry - working, but needs controller fix
Dark Souls: Prepare To Die Edition - working, fixed cinematics,

Added fixes for 200260 211420 220440 268910 35140

---

protonfixes/gamefixes/508980.py

To avoid a black screen at startup set `FSAA` to `0` in `graphics.config`.
https://www.protondb.com/app/508980

Add fix for Crashday Redline Edition (508980)

---

protonfixes/gamefixes/435150.py

Divinity OS 2 is a finnicky thing. It requires backing up the existing bin folder, then symlinking the bin folder from DefEd/ to the root game directory. This of course results in getting reset every update.  Additionally, after the symlink, on first launch the game will give a black screen. On subsequent launches the game runs fine.
The patch I've added makes the proper symlink only if EoCApp.exe is not detected in the /bin folder, as it doesn't exist in the original bin folder.  It will additionally give the user a prompt to let them know on first run the game will black screen, and that they must close and re-launch the game.
As mentioned, after this is done once, the script just runs the game accordingly until the next time an update resets the symlinks, in which case it performs the …

Fix for divinity original sin 2

---

protonfixes/gamefixes/200260.py
protonfixes/gamefixes/312670.py
protonfixes/gamefixes/35140.py

Batman Arkham City and Arkham Asylum don't need 32 bit prefixes any more, also they use the exact same dependencies. The corrections in this commit allow them to work OOTB including the launchers for both.
The Strange Brigade launcher renders all black. The script provided skips the launcher altogether and launches the Vulkan version of the game with the default launch options as if run by the launcher.

fixes for batman arkham city and asylum, fix for strange brigade

---

protonfixes/util.py

D9VK is disabled by default (because is a experimental translation layer) and disable_fsync is added (Proton 4.11 or above).

[util] Fix disable_d9vk and add disable_fsync

---

protonfixes/util.py

I did a quick fix for supporting new Proton (4.11-2) which changes how env, wine path etc are accessed. You can use this as a reference when making it compatible with newer Proton versions. Thought I'd share.
NOTE: I have not tested the prefix32 stuff. Please test that before merging!
Also, make a new release when done. I want to flag the AUR package (non-git one) as out of date :)

Update for new Proton, not backwards compatible

---

protonfixes/gamefixes/329380.py

We need `dsound` to have audio in this game.

Added gamefix for Stealth Inc 2: A Game of Clones

---

protonfixes/gamefixes/253230.py

Installing xact with winetricks causes the game to not launch at all on Proton 4.11-5 (for me atleast).
The game runs wine without it and has no audio issues.
I have played through the entire game with D9VK without issues.
Prefix needs to be deleted for the game to launch (so that xact doesn't get installed. Proton now comes with FAudio which works much better than xact)
D9VK is not needed but it lowers the stuttering and increases performance.

A Hat in Time: Don't install xact, enable D9VK

---

protonfixes/fix.py
protonfixes/gamefixes/default.py
protonfixes/util.py

tl;dr: Allow to use `protonfixes` from Steam launch options.
In particular:
1. Adds `default.py` "gamefix" support, both "global" and "local". Can be used to set some environment variables for all games. For example, I use this for `util.set_environment('__GL_SHOW_GRAPHICS_OSD', '1')`.
Only one of them used at a time, if exist, "local" have higher priority.
2. Adds `util.get_game_exe_name()`.
3. Adds `util.winecfg()`, `util.regedit()` and `util.control()`, which are aliases for corresponding Wine tools.
4. Adds `-pf_` prefixed aliases (**p**roton**f**ixes), to use as command line parameters.
Very basic, but something like `-pf_tricks=dsound  -pf_tricks=vcrun2017 -pf_winecfg` in Steam launch options should work. Commands after `-pf_tricks=` are normal `winetricks` commands.
Well, all this …

Steam launch options

---

protonfixes/engine.py

Very basic, barely tested, written in `mc` and not checked by ... TRAVIS! :rage4: API implementation.
Should be useful w/ previous PR, for things like `-pf_nointro` and/or `-pf_windowed`.
```python
from protonfixes.engine import engine
engine.windowed()
```
Just a rough attempt to detect game engine and use it's command line parameters to force windowed mode (thanks to recently broken Wine virtual desktop).
Mostly tested on Unity 5 game engine.

Added engine.py module

---

protonfixes/gamefixes/default.py
protonfixes/util.py

Example:
* `-pf_dxvk_set=dxvk.hud=full` - show Full DXVK HUD
* `-pf_dxvk_set=d3d9.presentInterval=0` - disable Vsync (D9VK)
* `-pf_dxvk_set=dxgi.syncInterval=0`    - disable Vsync (DXVK)
_Note: newer DXVK versions supports per-game configuration sections (e.g. `[GameName.exe]`), thus I added simple hack to add/remove `[DEFAULT]` section from the file. Should be reviewed at some point, but works for me so far._

Added `-pf_dxvk_set` alias for `set_dxvk_option()`

---

protonfixes/engine.py

Everything else seems works as expected.
For `-pf_nointro -pf_windowed -pf_dxvk_set=dxvk.hud=full`
**unknown game engine**
```
ProtonFixes[28597] INFO: Running protonfixes
ProtonFixes[28597] INFO: Engine: unknown Game engine
ProtonFixes[28597] INFO: Using local defaults for "Saints Row IV" (206420)
ProtonFixes[28597] WARN: nointro: Engine not defined
ProtonFixes[28597] WARN: windowed: Engine not defined
ProtonFixes[28597] INFO: Creating new DXVK config
ProtonFixes[28597] ADD: env: DXVK_CONFIG_FILE=/tmp/protonfixes_dxvk.conf
ProtonFixes[28597] ADD: DXVK: dxvk.hud = full
```
**known game engine**
```
ProtonFixes[23115] INFO: Running protonfixes
ProtonFixes[23115] INFO: Engine: Unity
ProtonFixes[23115] INFO: Engine: https://pcgamingwiki.com/wiki/Engine:Unity
ProtonFixes[23115] INFO: Using …
```

Fix engine module for unknown game engines

---

protonfixes/gamefixes/250180.py
protonfixes/gamefixes/366250.py
protonfixes/gamefixes/366260.py
protonfixes/splash.py

Fixes for Metal Slug 1, 2 and 3.
The fix is the one documented by Nothor on ProtonDB at
https://www.protondb.com/app/250180 which is to replace several DLL
files. This then allows the game to load and play without any errors and
no issues with black screens.

Fixes for Metal Slug games

---

protonfixes/__init__.py

AFAIK `waitforexitandrun` the only "action" which we should care about.
So,  we shouldn't attempt to run anything on the `run` proton's "actions".
Fixes multiple `WARN: Optional dependency cefpython3 not found` in the log file.

Do not import more then needed

---

protonfixes/engine.py

Python 3.8 has introduced a warning when the `is` operator is used inappropriately (see [this](https://bugs.python.org/issue34850) for a thorough explanation)  
The gist of the problem is that the use of the `is` operator for string comparison accidentally works on CPython (the standard python interpreter) however such behavior is not guaranteed with other python implementations or future versions of CPython
This PR replaces the `is` operator with `==` where applicable.

Fix 'SyntaxWarning: "is" with a literal. Did you mean "=="?' warning in engine.py

---

protonfixes/gamefixes/70400.py
protonfixes/gamefixes/70420.py

This PR add support for the following games:
70400 - Recettear: An Item Shop's Tale
70420 - Chantelise - A Tale of Two Sisters
Both fixes are identical since the underlying game engine is the same

Add protonfixes for Recettear and Chantelise

---

protonfixes/debug.py

`debug.py` errors out with `cannot import name 'basedir' from '__main__'`
This patch fixes it and restores full functionality

Fix debug.py

---

protonfixes/debug.py
protonfixes/protonmain_compat.py
protonfixes/util.py

As per title, this PR allows older versions of proton to work with protonfixes.
This is achieved via a proxy class that redirects attribute access to legacy proton attributes.
While this does not guarantee a 1:1 mapping between the old and new proton, it allows all the current functionality of `util.py` to work.
Due to the way that the redirect is accomplished if a future version of protonfixes wishes to drop support for older versions of proton all that is required is to remove the `protonmain_compat` import and use
```
import __main__ as protonmain
```

Make protonfixes work with older proton versions

---

protonfixes/config.py
protonfixes/fix.py

Sometimes user may want to disable predefined gamefixes.
For e.g. specific setups or testing purposes.

Allow global gamefixes to be disabled

---

protonfixes/debug.py
protonfixes/protonmain_compat.py
protonfixes/protonversion.py
protonfixes/util.py

Aggregate all the version-related functions of `protonmain_compat.py` and `utils.py` into `protonversion.py`
Improve version retrieval and checking by using the `version` file for both timestamp and release version (as it is more accurate than `CURRENT_PREFIX_VERSION`)
Implement `DeprecatedSince` decorator, when applied to a function and given a suitable version either in timestamp form (int) or version form (string) it will execute the function only if the version is lower (excluding) than the one specified, should be useful in cases outlined [here](https://github.com/simons-public/protonfixes/pull/111#issuecomment-591997293)

Add protonversion.py

---

protonfixes/config.py
protonfixes/download.py
protonfixes/fix.py
protonfixes/gamefixes/250180.py
protonfixes/gamefixes/366250.py
protonfixes/gamefixes/366260.py
protonfixes/gamefixes/379720.py
protonfixes/progress.py
protonfixes/splash.py
protonfixes/static/index.html
protonfixes/util.py

We have a progress bar :tada:  (should fix #8)
Minor things that have changed:
* `config.ini`: new config options
* `splash_preference`: order in which splashes are going to be tried
* `zenity_bigpicture`: allow zenity as splash in bigpicture mode
* `util.install_from_zip` has been moved to download in an effort to slim down utils and since it made more sense to be there
* metal slug fixes and doom have been modified to use `download.install_from_zip`, `install_from_zip` now has a `filesha` parameter like in the metal slug fixes
1. `TrackProgress` is created in `progress.py`, it has an internal registry
2. `fix.py` imports all the modules that have `TrackProgress`-decorated functions, the decorator is invoked and the internal registry is populated with fully-qualified function names that …

Splash overhaul

---

protonfixes/gamefixes/489830.py

Installing FAudio is needed for working dialog audio with NPCs.
This was discovered here: https://github.com/ValveSoftware/Proton/issues/4#issuecomment-415748747

 Added fixes for TES V: Skyrim Special Edition

---

protonfixes/splash.py

As the title states this fix will allow to launch protonfixes without kivy (App now is replaced with `object` in case kivy isn't present)
Also added a docstring to `SplashApp.on_start` that was causing a lint error
Closes #121

Fix splash.py in case kivy isn't installed, lint fix

---

protonfixes/gamefixes/228760.py
protonfixes/gamefixes/229870.py
protonfixes/gamefixes/232910.py
protonfixes/gamefixes/233050.py
protonfixes/gamefixes/233070.py
protonfixes/gamefixes/243360.py
protonfixes/gamefixes/264660.py
protonfixes/gamefixes/264850.py
protonfixes/gamefixes/600720.py
protonfixes/gamefixes/600730.py

In the compdata folder the games are linked via symlinks to the ManiaPlanet folder. This makes it possible to launch other trackmania games while running a mania planet game.
The renaming and resymlinking seems to work fast enough that the game doesn't crash at least on the systems i tested on. 
If someone might test it to confirm it would be helpful. The TrackMania Demos are free so easy candidates to test.

Needs Testing: Use one ManiaPlanet folder for all ManiaPlanet games

---

protonfixes/gamefixes/343090.py

SimpleRockets won't start without dotnet40
Fix reported by folks on ProtonDB: https://www.protondb.com/app/343090

Add fix for SimpleRockets

---

protonfixes/gamefixes/1113000.py

Note that this requires a recent version of winetricks (20200412) to install wmp9 in 64-bit prefixes.

add fixes for Persona 4 Golden

---

protonfixes/gamefixes/729040.py

Currently Borderlands GOTY's launcher does not work so must be replaced
with the game executable to be made playable. This commit adds code to
do this in a way that can be overridden by setting a environment
variable called "KEEP_LAUNCHER" to any value in the game's launch
command.

Make the Borderlands GOTY fix replace launcher

---

protonfixes/gamefixes/228260.py
protonfixes/gamefixes/263980.py
protonfixes/gamefixes/280200.py
protonfixes/gamefixes/312530.py
protonfixes/gamefixes/359320.py
protonfixes/gamefixes/394540.py
protonfixes/gamefixes/91100.py
protonfixes/util.py

This PR includes some small fixes for the following games:
* Out There Somewhere (263980)
* Spaceport Hope (394540)
* Elite Dangerous (359320)
* Duck Game (312530)
* Eterium (280200)
* SkyDrift (91100)
* Fallen Enchantress: Legendary Heroes (228260)
I also took the liberty of adding the env `PROTON_USE_WINED3D` in `utils.disable_dxvk` to future-proof its use, since the environment variable `PROTON_USE_WINED3D11` was removed from the proton documentation a while ago, and might be deprecated in the future

Various New Fixes

---

protonfixes/gamefixes/228760.py
protonfixes/gamefixes/229870.py
protonfixes/gamefixes/232910.py
protonfixes/gamefixes/233050.py
protonfixes/gamefixes/233070.py
protonfixes/gamefixes/243360.py
protonfixes/gamefixes/264660.py
protonfixes/gamefixes/264850.py
protonfixes/gamefixes/600720.py
protonfixes/gamefixes/600730.py

The previous scripts did not work because of a bug in line 32. It should've been `os.remove(game_path)` instead of `os.remove(game_id)`.
Instead of simply fixing the bug I decided to add some features:
* Only symlink the wine pfx, not the whole bottle
* Try copying everything from the old prefixes into the new prefix (does not yet work for filenames containing special chars like & or whitespace, no clue why)
* Before, only the contents of one game would've been copied and everything else would've been deleted.
* Before, the for loop for deleting and linking all other games had too big indentation, so it would never run anyways.

Improve handling for all ManiaPlanet Titles

---

protonfixes/gamefixes/718850.py

Start the game instead of the launcher because the launcher crashes.

Add fix for Age of Wonders: Planetfall

---

README.md

Ubuntu, Debian and derivatives do not have pip installed by default. This clarifies the installation of the pip package on these distros:
> If you are unsure, try installing with both pip3 and pip2 before running the commands below (`python3-pip` and `python2-pip` on Ubuntu/Debian-based distributions).

README: Clarify pip installation on Ubuntu/Debian/derivatives

---

protonfixes/gamefixes/1113000.py

Additionally requires lavfilters to work with version 1.1 of the game.
https://www.protondb.com/app/1113000
https://github.com/GloriousEggroll/protonfixes/commit/997a0b4a5d799342e412f420211d43aaeb90af83
The lavfilters verb has been added to winetricks with
https://github.com/Winetricks/winetricks/commit/8b999767e166c16692cfa10dfc7f31f5c13adab9
and is included in the 20201206 release.

Update 1113000.py (Persona 4 Golden)

---

protonfixes/corefonts.py

Fixes #147
The second argument to `urlopen` is the data sent to the server. The server doesn't want any data on our local files, so it replies with 403.
After removing the argument, #147 no longer reproduced.

Fix corefonts.py getting 403

---

protonfixes/gamefixes/287260.py

The game has infinite loading screens when esync is not disabled.
I haven't tested this with protonfixes (yet) but setting `PROTON_NO_ESYNC=1` fixed the problem.

Game fix for Toybox Turbos (287260)

---

scripts/soldier_protonfixify

Soldier now is installed in a different directory, so the `soldier_protonfixify` script needs to be updated
Contents of this PR:
* saner options for the script, with `set -euo pipefail` for extra robustness
* updated one of the debian dependencies that otherwise would not be downloaded
* Now the script logs errors & major console spams to `/tmp/protonfixify.log` to allow easier debugging
* The install root of soldier has changed location, the script checks for both variations just in case
I don't know if #154 is related, but it would be worth checking if @Zyneris has the same problem after clearing the `.protonfixify` file inside the soldier folder and  rerunning `install_protonfixes`

Fix soldier_protonfixify script

---

protonfixes/gamefixes/63600.py

icodecs is necessary to show in-game videos and also fixes framerate issues

Add game fix for realMyst

---

protonfixes/util.py

Setting e.g. `util.set_environment('SOMEPATH', '/usr/lib/somedir:/usr/lib64/somedir', ':')`
will append given paths to the end of `SOMEPATH` environment variable.
_Well, "prepend" also makes sense in some rare situations._

Extend set_environment

---

protonfixes/gamefixes/684450.py

This fix bypasses the Paradox launcher to be able to launch Surviving the Aftermath.

Add compatibility for 684450

---

protonfixes/gamefixes/495420.py

Added `d3dcompiler_47` to prevent game crashes and `win7` to fix multiplayer and prevent multiplayer crashes.

Added a fix for State of Decay 2 Crashes

---

protonfixes/gamefixes/910830.py

mfc42 needs to be installed for the game to run. Tested with Proton 7.0-3

Add fix for Rebel Galaxy Outlaw

---

protonfixes/gamefixes/1097880.py

just as the title implies these options allow the game to run without a black screen.
win64 wasn't really reliable but win32 is.

adding support for Super Naughty Maid 2

---

protonfixes/gamefixes/287310.py

Game needs proper dll overrides to work on newer Proton versions.
See: https://www.protondb.com/app/287310

Add protonfix for Re-Volt (287310)
