- protonfixes/fix.py
Example:
```
ProtonFixes[4276] INFO: Running protonfixes
ProtonFixes[4276] INFO: Using local protonfix for "The Witcher 3: Wild Hunt" (292030)
```
Fixes #22
> Added automated game name logging

- protonfixes/gamefixes/242920.py
Banished needs `xact` to be installed and `xaudio2_7` set to native.
> Added fix for Banished

- protonfixes/fix.py
When running proton manually I get `IndexError: list index out of range` from [Line 35](https://github.com/simons-public/protonfixes/blob/master/protonfixes/fix.py#L35) so let's catch that error too.
This probably happens because the `$PWD` is in an unexpected directory.
> IndexError: list index out of range

- protonfixes/gamefixes/480.py
>  Added fix for Spacewar 

- protonfixes/gamefixes/307690.py
I create some fix for Sleeping Dogs: Definitive Edition.
> Add fixes for Sleeping Dogs: Definitive Edition (307690)

- protonfixes/gamefixes/111600.py
Fixes needed:
* Install dotnet40
> Add fixes for Serious Sam Double D XXL (111600)

- protonfixes/util.py
This should fix annoying reinstallation of some already installed verbs.
Examples:
* `vd=off`
* `vd=1920x1080`
Will record such verbs into separate file, and perform checks on next run.
Fixes: #11
> Manually record verbs not recorded by winetricks

- protonfixes/util.py
Example (setting random options):
```python
user_opts = """
[LoadingScreen/Debug]
DisableVideos=true
[LevelOfDetail]
DynamicDecalsHideDistance=60
[Rendering]
TextureMipBias=-1
"""
util.set_ini_options(user_opts, 'The Witcher 3/user.settings')
game_opts = """
[Rendering]
TextureMipBias=-0.7
"""
util.set_ini_options(game_opts, '../config/base/rendering.ini', 'game')
```
Closing: #21
> Added util.set_ini_options()

- protonfixes/fix.py
- protonfixes/logger.py
> Fix game names containing unicode characters

- protonfixes/gamefixes/593600.py
The gamefix overrides the mprapi.dll to native
> Added gamefix for PixARK

- protonfixes/util.py
> add proton_4.11 option

- protonfixes/util.py
Utility function to disable the UPlay in-game overlay.
> util.disable_uplay_overlay()

- protonfixes/debug.py
- protonfixes/download.py
- protonfixes/gamefixes/211600.py
- protonfixes/gamefixes/211740.py
- protonfixes/util.py
This is quite a big changeset, it mainly adds the fix for thief 1&2 but also adds some additional functionality.
Changes:
* Fix for Thief 1&2
* util.py: new function wine_run for running exes (in this case the TFix)
* download.py: download-related functions, right now can download a google drive file and do sha1sum of a file
> Add fixes for Thief 1&2  and related changes

- README.md
- scripts/install_protonfixes
- setup.py
As stated in the title, this PR adds a script called `install_protonfixes` which will search all possible proton locations and attempt to install protonfixes in all of then.
> Add install_protonfixes script

- protonfixes/gamefixes/21690.py
- protonfixes/gamefixes/221040.py
- protonfixes/gamefixes/222480.py
- protonfixes/gamefixes/287290.py
- protonfixes/gamefixes/289620.py
- protonfixes/gamefixes/304240.py
- protonfixes/gamefixes/339340.py
- protonfixes/gamefixes/6020.py
- protonfixes/gamefixes/6030.py
- protonfixes/gamefixes/729040.py
- protonfixes/gamefixes/7850.py
valve added oldglstr for 6020 and 6030 already, so deprecate.
> deprecate and add batch of fixes

- .gitignore
- protonfixes/gamefixes/243470.py
> Watch_Dogs (243470)

- protonfixes/gamefixes/1030830.py
See Proton Issue https://github.com/ValveSoftware/Proton/issues/3891
> Add Fix for Mafia II: Definitive Edition

- protonfixes/gamefixes/913740.py
esync causes occasional crashes
> Add fixes for WORLD OF HORROR

- protonfixes/gamefixes/758330.py
Adds fix for Shenmue I & II so that the launcher and audio works properly. Makes the game work out of the box once applied.
> Add fix for Shenmue I & II

- protonfixes/gamefixes/261640.py
Same issue with Borderlands 2.
> Borderlands: The Pre-Sequel replace launcher fix

- protonfixes/gamefixes/238090.py
replace launcher to avoid 'dot in pathname issue'. see proton issue https://github.com/ValveSoftware/Proton/issues/2866
> Add fix for Sniper Elite 3:

- protonfixes/gamefixes/321960.py
- protonfixes/gamefixes/445310.py
Install uplay as required by the game.
> Add fix for Might & Magic: Heroes VII (- Trial by Fire)

- protonfixes/gamefixes/769560.py
As described at https://blog.csdn.net/AsWeDo/article/details/104564587
> Fix for Night of the Full Moon

- protonfixes/gamefixes/638970.py
Fixes the issues where saving the game does only randomly work and fails (silently) most of the time. For details also see:
* https://github.com/ValveSoftware/Proton/issues/492
* https://www.protondb.com/app/638970
> Add fix for Yakuza 0

- protonfixes/gamefixes/834530.py
https://github.com/ValveSoftware/Proton/issues/2403
https://www.protondb.com/app/834530
> Add fix for Yakuza Kiwami

- README.md
Just a minor thing I ran into while reading about the software.
> Fixed typo, added link to Wiki

- docs/Writing-Gamefixes.md
> docs: Specify file to add debugging line
